### ISSUE TITLE
Delete apps that arent used

### ISSUE THREAD

**Issue by Hhhonlyfan** [coder8338/appbox_installer#62] opened 2022-03-16 16:49 UTC
Hi,

Is there a way or can it be added where you can delete apps if no longer needed or causing issues?

i ask because i get issues with sonarr (both skyhook errors and errors with adding usenet providers) i dont want to wipe all the apps but just this one for instace.

**Comment by coder8338** [comment] 2022-03-17 08:17
Closing, dupe of https://github.com/coder8338/appbox_installer/issues/40

**Closed as completed by coder8338** 2022-03-17 08:17 UTC
